/**
 * STUB Brand Playbook skill.
 *
 * This will be replaced with the real Claude Code skill handed off by Buzz.
 * Contract: takes BrandIntake + outputDir, writes named files, returns a manifest.
 * The real skill (per IEI brief slide 05) uses Playwright + PIL to render a
 * 360 DPI PDF. That pipeline lands in Day 3.
 */
import fs from "node:fs";
import path from "node:path";
import type { BrandIntake, BrandJson } from "@/lib/types";

export type SkillManifest = {
  brandJson: string;
  playbookHtml: string;
  landingHtml: string;
  logoSvg: string;
};

const PALETTE_BY_ARCHETYPE: Record<string, BrandJson["colors"]> = {
  hero: { primary: "#0F172A", secondary: "#DC2626", accent: "#F59E0B", neutral: "#F8FAFC" },
  sage: { primary: "#1E3A8A", secondary: "#0EA5E9", accent: "#CBD5E1", neutral: "#F9FAFB" },
  creator: { primary: "#7C3AED", secondary: "#EC4899", accent: "#FBBF24", neutral: "#FAFAFA" },
  caregiver: { primary: "#065F46", secondary: "#D97706", accent: "#FDE68A", neutral: "#FFFBEB" },
  default: { primary: "#111827", secondary: "#2563EB", accent: "#F97316", neutral: "#F3F4F6" },
};

function synthesizeBrand(intake: BrandIntake): BrandJson {
  const key = (intake.archetype || "").toLowerCase() as keyof typeof PALETTE_BY_ARCHETYPE;
  const colors = PALETTE_BY_ARCHETYPE[key] ?? PALETTE_BY_ARCHETYPE.default;
  return {
    name: intake.companyName,
    tagline: `Brand direction for ${intake.companyName} — ${intake.industry}`,
    colors,
    typography: { heading: "Geist, Inter, sans-serif", body: "Geist, Inter, sans-serif" },
    tone: intake.toneOfVoice.split(",").map((s) => s.trim()).filter(Boolean),
    positioning: `${intake.companyName} serves ${intake.targetAudience} in ${intake.industry}.`,
  };
}

function renderPlaybookHtml(b: BrandJson, intake: BrandIntake): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"/><title>${b.name} — Brand Playbook</title>
<style>
  :root { --p:${b.colors.primary}; --s:${b.colors.secondary}; --a:${b.colors.accent}; --n:${b.colors.neutral}; }
  body { font-family: ${b.typography.body}; margin: 0; color: #0b0b0b; background: var(--n); }
  .page { max-width: 820px; margin: 0 auto; padding: 64px 48px; }
  h1 { font-size: 48px; margin: 0 0 8px; color: var(--p); letter-spacing: -0.02em; }
  h2 { font-size: 22px; margin: 48px 0 12px; color: var(--p); }
  .tag { color: #555; font-size: 18px; }
  .swatches { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
  .sw { aspect-ratio: 1; border-radius: 12px; display: flex; align-items: flex-end; padding: 12px; color: #fff; font-family: monospace; font-size: 13px; }
  .sw.light { color: #111; }
  .pill { display: inline-block; padding: 6px 12px; border-radius: 999px; background: #fff; border: 1px solid #e5e7eb; margin: 4px 6px 0 0; font-size: 14px; }
  .kv { display: grid; grid-template-columns: 160px 1fr; gap: 12px 20px; }
  .kv dt { color: #666; }
</style></head>
<body><div class="page">
  <h1>${b.name}</h1>
  <div class="tag">${b.tagline}</div>

  <h2>Positioning</h2>
  <p>${b.positioning}</p>

  <h2>Color System</h2>
  <div class="swatches">
    <div class="sw" style="background:${b.colors.primary}">${b.colors.primary}</div>
    <div class="sw" style="background:${b.colors.secondary}">${b.colors.secondary}</div>
    <div class="sw" style="background:${b.colors.accent}">${b.colors.accent}</div>
    <div class="sw light" style="background:${b.colors.neutral}">${b.colors.neutral}</div>
  </div>

  <h2>Typography</h2>
  <div class="kv">
    <dt>Heading</dt><dd>${b.typography.heading}</dd>
    <dt>Body</dt><dd>${b.typography.body}</dd>
  </div>

  <h2>Tone of Voice</h2>
  <div>${b.tone.map((t) => `<span class="pill">${t}</span>`).join("")}</div>

  <h2>Intake Summary</h2>
  <div class="kv">
    <dt>Industry</dt><dd>${intake.industry}</dd>
    <dt>Audience</dt><dd>${intake.targetAudience}</dd>
    <dt>Competitors</dt><dd>${intake.competitors || "—"}</dd>
    <dt>Archetype</dt><dd>${intake.archetype || "—"}</dd>
    <dt>Notes</dt><dd>${intake.notes || "—"}</dd>
  </div>

  <p style="margin-top:64px;color:#9ca3af;font-size:12px">Generated by IEI Ventures (stub skill). Real Brand Playbook skill swaps in Day 3.</p>
</div></body></html>`;
}

function renderLandingHtml(b: BrandJson): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"/><title>${b.name}</title>
<style>
  body { margin:0; font-family:${b.typography.body}; color:#0b0b0b; background:${b.colors.neutral}; }
  .hero { min-height:70vh; display:flex; flex-direction:column; justify-content:center; padding:80px 40px; background:linear-gradient(135deg, ${b.colors.primary}, ${b.colors.secondary}); color:#fff; }
  .hero h1 { font-size:64px; margin:0 0 16px; letter-spacing:-0.03em; }
  .hero p { font-size:22px; opacity:.9; max-width:640px; }
  .cta { display:inline-block; margin-top:32px; padding:16px 28px; background:${b.colors.accent}; color:#111; border-radius:999px; text-decoration:none; font-weight:600; }
  .section { max-width:960px; margin:0 auto; padding:80px 40px; }
  .section h2 { color:${b.colors.primary}; font-size:32px; margin:0 0 16px; }
</style></head>
<body>
  <section class="hero">
    <h1>${b.name}</h1>
    <p>${b.tagline}</p>
    <a class="cta" href="#contact">Get in touch</a>
  </section>
  <section class="section">
    <h2>What we do</h2>
    <p>${b.positioning}</p>
  </section>
  <section class="section" id="contact">
    <h2>Contact</h2>
    <p>Replace this block with your contact details.</p>
  </section>
</body></html>`;
}

function renderLogoSvg(b: BrandJson): string {
  const initials = b.name
    .split(/\s+/)
    .map((w) => w[0])
    .filter(Boolean)
    .slice(0, 2)
    .join("")
    .toUpperCase() || "IV";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" width="200" height="200">
  <rect width="200" height="200" rx="32" fill="${b.colors.primary}"/>
  <text x="100" y="118" text-anchor="middle" font-family="Geist, Inter, sans-serif" font-weight="700" font-size="72" fill="${b.colors.accent}">${initials}</text>
</svg>`;
}

export async function runBrandPlaybook(
  intake: BrandIntake,
  outputDir: string
): Promise<SkillManifest> {
  fs.mkdirSync(outputDir, { recursive: true });
  const brand = synthesizeBrand(intake);

  const files = {
    brandJson: "brand.json",
    playbookHtml: "playbook.html",
    landingHtml: "landing.html",
    logoSvg: "logo.svg",
  };

  fs.writeFileSync(path.join(outputDir, files.brandJson), JSON.stringify(brand, null, 2));
  fs.writeFileSync(path.join(outputDir, files.playbookHtml), renderPlaybookHtml(brand, intake));
  fs.writeFileSync(path.join(outputDir, files.landingHtml), renderLandingHtml(brand));
  fs.writeFileSync(path.join(outputDir, files.logoSvg), renderLogoSvg(brand));

  return files;
}
